# Generated by Django 3.0.6 on 2020-09-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200912_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor_feedback',
            name='plasma_bank',
            field=models.IntegerField(),
        ),
    ]
